// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq5KQ9guAzQHQGUq0wfGJqt3ud2ZBgzNo',
    appId: '1:883399336230:web:7570512fc9a9309a6aa1e7',
    messagingSenderId: '883399336230',
    projectId: 'sikawan-001',
    authDomain: 'sikawan-001.firebaseapp.com',
    databaseURL: 'https://sikawan-001-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sikawan-001.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBah9qO6dNSjkRLhu9Mw3IeUdQx_nzsTwg',
    appId: '1:883399336230:android:d7f6084f8e0da60d6aa1e7',
    messagingSenderId: '883399336230',
    projectId: 'sikawan-001',
    databaseURL: 'https://sikawan-001-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sikawan-001.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSzV4lp9MZjyzehXiioBU1EWk0XVgl5NU',
    appId: '1:883399336230:ios:dc97b0091a2918b36aa1e7',
    messagingSenderId: '883399336230',
    projectId: 'sikawan-001',
    databaseURL: 'https://sikawan-001-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sikawan-001.appspot.com',
    iosBundleId: 'com.example.presensiMobileApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSzV4lp9MZjyzehXiioBU1EWk0XVgl5NU',
    appId: '1:883399336230:ios:fd5b86d042cfc51e6aa1e7',
    messagingSenderId: '883399336230',
    projectId: 'sikawan-001',
    databaseURL: 'https://sikawan-001-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sikawan-001.appspot.com',
    iosBundleId: 'com.example.presensiMobileApps.RunnerTests',
  );
}
